# Generated by Django 4.2.2 on 2023-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="School_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("founded_year", models.PositiveIntegerField()),
                ("principal_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("website", models.URLField()),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("total_students", models.PositiveIntegerField()),
                ("total_staff", models.PositiveIntegerField()),
            ],
        ),
    ]
